title: Screensaver Documentation 
email: sean_erickson@hms.harvard.edu
description: "Screensaver HTS LIMS: Open source software for high throughput screening"
baseurl: "/screensaver-docs" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com

aux_links:
  "Screensaver on GitHub":
    - "//github.com/hmsiccbl/screensaver"


back_to_top: true
back_to_top_text: "Back to top"

footer_content: "&copy; 2021 <a href=\"https://iccb.med.harvard.edu/\">ICCB-Longwood</a>. Distributed by an <a href=\"\">MIT license.</a>"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y" # format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Build settings

search_enabled: true
heading_anchors: true

theme: just-the-docs 
#remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-seo-tag


exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false


